# Generated by Django 3.1.4 on 2020-12-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('0', 'INGRESO'), ('1', 'EGRESO')], max_length=50, verbose_name='Tipo')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partida.partida')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
