# Generated by Django 3.1.4 on 2020-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_auto_20201215_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='concepto',
            field=models.FloatField(default=0),
        ),
    ]
