# Generated by Django 3.1.4 on 2020-12-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0003_partida_concepto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='items',
            new_name='partida_superior',
        ),
    ]
