# Generated by Django 3.1.4 on 2020-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0004_auto_20201215_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='concepto',
            field=models.CharField(max_length=5, verbose_name='Concepto'),
        ),
    ]
