# Generated by Django 3.1.4 on 2020-12-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0009_auto_20201215_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='concepto',
            field=models.CharField(max_length=50, verbose_name='Concepto'),
        ),
    ]
