# Generated by Django 3.1.4 on 2020-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0012_auto_20201215_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='concepto',
            field=models.CharField(max_length=60, verbose_name='Concepto'),
        ),
    ]
